# Generated by Django 5.1.6 on 2025-02-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(default=0)),
                ('section', models.CharField(choices=[('preparation', 'Preparation Steps'), ('execution', 'Execution Steps'), ('wrapup', 'Wrap-Up Steps')], max_length=20)),
                ('step', models.CharField(max_length=255)),
                ('procedure', models.TextField(blank=True)),
                ('day_time_duration', models.CharField(blank=True, max_length=100)),
                ('nq_duration', models.CharField(blank=True, max_length=100)),
                ('executor', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['section', 'step_order'],
            },
        ),
    ]
