# Generated by Django 5.1.6 on 2025-02-22 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='testplanstep',
            name='testplan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='testplan.testplan'),
            preserve_default=False,
        ),
    ]
