# Generated by Django 5.1.6 on 2025-02-22 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0002_testplan_testplanstep_testplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('section', models.CharField(choices=[('preparation', 'Preparation Steps'), ('execution', 'Execution Steps'), ('wrapup', 'Wrap-Up Steps')], max_length=20)),
                ('procedure', models.TextField(blank=True)),
                ('day_time_duration', models.CharField(blank=True, max_length=100)),
                ('nq_duration', models.CharField(blank=True, max_length=100)),
                ('executor', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(default=0)),
                ('section', models.CharField(choices=[('preparation', 'Preparation Steps'), ('execution', 'Execution Steps'), ('wrapup', 'Wrap-Up Steps')], max_length=20)),
                ('step', models.CharField(max_length=255)),
                ('procedure', models.TextField(blank=True)),
                ('day_time_duration', models.CharField(blank=True, max_length=100)),
                ('nq_duration', models.CharField(blank=True, max_length=100)),
                ('executor', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='testplan.testplantemplate')),
            ],
            options={
                'ordering': ['section', 'step_order'],
            },
        ),
    ]
