# Generated by Django 5.1.6 on 2025-02-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0003_predefinedstep_testplantemplate_templatestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedstep',
            name='folder',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='testplantemplate',
            name='folder',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
