# Generated by Django 5.1.6 on 2025-02-23 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0004_predefinedstep_folder_testplantemplate_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(default=dict)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('testplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='testplan.testplan')),
            ],
        ),
    ]
